### ISSUE TITLE
New stuff enhancements

### ISSUE THREAD

**Issue by Druivenpasta** [CuboidDroid/cuboidmod#3]
So basically I've been messinng around with coding everything, and is there a way to program more singularities? And can the recipes for them be added trough kubejs? 
Waiting for response!

**Comment by CuboidDroid** [comment]
Hi. It's not really possible with the current version. As I mentioned recently, I'm working on standalone mods which will be more suited to use in other packs. It will be possible in that mod to make your own singularities through config
